local FT_TOOLS = {
	lua = { lsp = "lua-language-server", formatter = "stylua", linter = "luacheck" },
	typescript = { lsp = "typescript-language-server", formatter = "prettierd", linter = "eslint-ls" },
	typescriptreact = { lsp = "typescript-language-server", formatter = "prettierd", linter = "eslint-ls" },
	javascript = { lsp = "typescript-language-server", formatter = "prettierd", linter = "eslint-ls" },
	javascriptreact = { lsp = "typescript-language-server", formatter = "prettierd", linter = "eslint-ls" },
	json = { lsp = "json-lsp", formatter = "prettierd" },
	jsonc = { lsp = "json-lsp", formatter = "prettierd" },
	python = { lsp = { "pylsp", "ruff-lsp" }, formatter = { "black", "isort" }, linter = { "ruff", "mypy" } },
	go = { lsp = "gopls", formatter = "gofumpt", linter = "golangci-lint" },
	gomod = { lsp = "gopls" },
	gowork = { lsp = "gopls" },
	rust = { lsp = "rust-analyzer", formatter = "rustfmt" },
	c = { lsp = "clangd", formatter = "clang-format", linter = "cpplint" },
	cpp = { lsp = "clangd", formatter = "clang-format", linter = "cpplint" },
	java = { lsp = "jdtls", formatter = "google-java-format" },
	cs = { lsp = "csharp-language-server" },
	php = { lsp = "intelephense", formatter = "php-cs-fixer", linter = { "phpcs", "phpstan" } },
	ruby = { lsp = "ruby-lsp", formatter = "rubocop", linter = "rubocop" },
	haskell = { lsp = "haskell-language-server", formatter = "ormolu", linter = "hlint" },
	elixir = { lsp = "elixir-ls" },
	erlang = { lsp = "erlang-ls" },
	dart = { lsp = "dartls", formatter = "dart-format" },
	kotlin = { lsp = "kotlin-language-server", formatter = "ktfmt", linter = "ktlint" },
	swift = { formatter = "swiftformat", linter = "swiftlint" },
	zig = { lsp = "zls" },
	nim = { lsp = "nimlangserver" },
	scala = { lsp = "metals" },
	r = { lsp = "r-languageserver" },
	julia = { lsp = "julialsp" },
	sh = { lsp = "bash-language-server", linter = "shellcheck" },
	bash = { lsp = "bash-language-server", linter = "shellcheck" },
	zsh = { lsp = "bash-language-server", linter = "shellcheck" },
	ps1 = { lsp = "powershell-editor-services" },
	html = { lsp = "html-lsp", formatter = "prettierd" },
	css = { lsp = "css-lsp", formatter = "prettierd" },
	scss = { lsp = "css-lsp", formatter = "prettierd" },
	less = { lsp = "css-lsp", formatter = "prettierd" },
	sass = { lsp = "some-sass-language-server", formatter = "prettierd" },
	xml = { formatter = "xmlformatter" },
	yaml = { lsp = "yaml-language-server", linter = "yamllint" },
	yml = { lsp = "yaml-language-server", linter = "yamllint" },
	toml = { lsp = "taplo" },
	markdown = { lsp = "marksman", linter = "markdownlint" },
	markdown_inline = { lsp = "marksman" },
	dockerfile = { lsp = "dockerfile-language-server", linter = "hadolint" },
	terraform = { lsp = "terraform-ls", formatter = "terraform_fmt", linter = "tflint" },
	hcl = { lsp = "terraform-ls" },
	sql = { lsp = "sqls", formatter = "sql-formatter" },
	graphql = { lsp = "graphql-language-service-cli", formatter = "prettierd" },
	proto = { lsp = "protols", formatter = "buf", linter = "protolint" },
	nix = { lsp = "nil", formatter = "nixfmt" },
	elm = { lsp = "elm-language-server", formatter = "elm-format" },
	clojure = { lsp = "clojure-lsp", linter = "clj-kondo" },
	fsharp = { lsp = "fsautocomplete" },
	tex = { lsp = "texlab" },
	latex = { lsp = "texlab" },
	vue = { lsp = "vue-language-server", formatter = "prettierd" },
	svelte = { lsp = "svelte-language-server", formatter = "prettierd" },
	astro = { lsp = "astro-language-server", formatter = "prettierd" },
	angular = { lsp = "angular-language-server" },
	ember = { lsp = "ember-language-server" },
	prisma = { lsp = "prisma-language-server" },
	tailwindcss = { lsp = "tailwindcss-language-server" },
	eslint = { lsp = "eslint-ls" },
	["docker-compose"] = { lsp = "docker-compose-language-service" },
	ansible = { lsp = "ansible-language-server", linter = "ansible-lint" },
	helm = { lsp = "helm-ls" },
	cmake = { lsp = "cmake-language-server", linter = "cmakelint" },
	meson = { lsp = "mesonlsp" },
	bzl = { lsp = "bazelrc-lsp" },
	groovy = { lsp = "groovy-language-server" },
	kscript = { lsp = "kotlin-language-server" },
	v = { lsp = "v-analyzer" },
	fennel = { lsp = "fennel-language-server" },
	teal = { lsp = "teal-language-server" },
	luau = { lsp = "luau-lsp" },
	wgsl = { lsp = "wgsl-analyzer" },
	glsl = { lsp = "glsl_analyzer" },
	vhdl = { lsp = "vhdl_ls" },
	verilog = { lsp = "verible" },
	systemverilog = { lsp = "verible" },
	asm = { lsp = "asm-lsp" },
	make = { linter = "checkmake" },
	caddyfile = { lsp = "caddyfile-lsp" },
	nginx = { lsp = "nginx-language-server" },
	elisp = { lsp = "emmylua_ls" },
	lisp = { lsp = "common-lisp-language-server" },
	scheme = { lsp = "racket-langserver" },
	racket = { lsp = "racket-langserver" },
	ocaml = { lsp = "ocamllsp", formatter = "ocamlformat" },
	reason = { lsp = "reason-language-server" },
	purescript = { lsp = "purescript-language-server", formatter = "purescript-tidy" },
	idris = { lsp = "idris2-lsp" },
	coq = { lsp = "coq-lsp" },
	lean = { lsp = "lean-language-server" },
	agda = { lsp = "agda-language-server" },
	apl = { lsp = "apl-language-server" },
	ada = { lsp = "ada-language-server" },
	cobol = { lsp = "cobol-language-support" },
	fortran = { lsp = "fortls", formatter = "fprettify" },
	pascal = { lsp = "pascal-language-server" },
	delphi = { lsp = "pascal-language-server" },
	objc = { lsp = "clangd", formatter = "clang-format" },
	arduino = { lsp = "arduino-language-server" },
	solidity = { lsp = "solidity-ls", linter = "solhint" },
	vyper = { lsp = "vyper-ls" },
	move = { lsp = "move-analyzer" },
	cairo = { lsp = "cairo-language-server" },
	gitcommit = { linter = "commitlint" },
	dotenv = { linter = "dotenv-linter" },
	editorconfig = { linter = "editorconfig-checker" },
	typst = { lsp = "tinymist", formatter = "typstyle" },
	pandoc = { linter = "vale" },
	text = { linter = "vale" },
}

return FT_TOOLS
