---@meta
---
---@class cat.lsp.config: vim.lsp.config
---@class cat.pkg.name: string
---
---@class cat.pkg
---@field name cat.pkg.name
---@field install fun(): nil
---@field installed boolean
---@field sync_config fun(cfg?: cat.lsp.config, default: cat.lsp.config): boolean
---
---@class cat.lsp: cat.pkg
---@field lspname cat.pkg.name
---@field lspconfig? cat.lsp.config
---
---@alias cat.lsp.spec cat.pkg.name|cat.pkg.name[]|cat.lsp.config
---
---@class cat.lsp.group: table<string>
---@field lsp? cat.lsp.spec
---
---@class cat.opts.lsp
---@field default_config? cat.lsp.config Default configuration for LSPs
---@field extensions? cat.lsp.group
---@field filetypes? cat.lsp.group
---
---@class cat.provider
---@field resolve fun(name: cat.pkg.name): cat.pkg|cat.lsp|nil
