---@meta
---
---@alias LspConfig vim.lsp.Config
---@alias LspName string
---@alias PkgName string
---@alias PkgCategory "DAP"|"Formatter"|"Linter"|"Runtime"|"LSP"
---@alias FileType string
---@alias FileExtension string
---
---@alias LspEntry LspName|LspName[]|table<LspName, LspConfig>
---
---@class LspByGroup
---@field lsps? LspEntry[]
---@field filetypes? FileType[]
---@field extensions? FileExtension[]
---@alias LspByFt table<FileType, LspEntry>
---@alias LspByExt table<FileExtension, LspEntry>
---
---@class Lsp
---@field name LspName
---@field config? LspConfig
---
---@class Pkg
---@field lsp? Lsp
---@field name PkgName
---@field install fun(): nil
---@field categories PkgCategory[]
---
---@class LspSetupOpts
---@field default_config? LspConfig
---@field by_group? LspByGroup
---@field by_ext? LspByExt
---@field by_ft? LspByFt
---
---@class CatalogSetupOpts
---@field debug? boolean
---@field silent? boolean
---@field lsp? LspSetupOpts
---@field integrations? string[]
---@field ensure_installed? PkgName[]
