---@meta
---
---=== DATA WRAPPER ===
---Package name in mason registry
---@class PkgName: string
---Package lspconfig name
---@class LspName: string
---Filetype
---@class Filetype: string
---Possibly categories mason packages
---@alias PkgCategories "Compiler"|"DAP"|"Formatter"|"LSP"|"Linter"|"Runtime"
---
---=== ENTITY ===
---@class Pkg
---@field name PkgName @ Mason package name
---@field lspname? LspName @ Associated lspconfig server
---@field categories PkgCategories[]
---@field install fun(): nil @ Installs the package via Mason
---
---=== DATA ===
---Defines how LSPs are declared:
--- - string: single LSP
--- - string[]: multiple LSPs
--- - table: LSP with custom config
---@alias LspEntry LspName|LspName[]|table<LspName, vim.lsp.Config>
---@alias NormalizedLsp table<LspName, vim.lsp.Config> @ Final LSP config map used for setup
---
---@alias LspByFt table<Filetype, LspEntry>
---@alias LspByGroup { filetypes: Filetype|Filetype[], lsps: LspEntry }
---
---@class EnsureList
---@field ensure fun(name: PkgName): Pkg? # Ensures a single package is installed (idempotent)
---@field ensure_many fun(list: PkgName[]): nil # Ensures multiple packages are installed
---@field ensure_any fun(input: PkgName|PkgName[]): nil # Accepts a single name or list and ensures all
---
---=== SETUP OPTS ===
---@class MasonCatalogLspOpts
---@field by_ft? LspByFt
---@field auto_enable? boolean
---@field by_group? LspByGroup[]
---@field default_config? vim.lsp.Config
---
---@class MasonCatalogSetupOpts
---@field lsp? MasonCatalogLspOpts @ LSP configuration options
---@field debug? boolean
---@field silent? boolean
---@field integrations? string|string[] @ Enabled integrations
---@field ensure_installed? PkgName|PkgName[] @ Mason packages to ensure installed
